### ISSUE TITLE
How to integrate new ReactiveCocoa/Swift/ObjC/ObjCBridge specs?

### ISSUE THREAD

**Issue by loveforgeter** [mhuusko5/Podspecs#15]
Very glad to see this at [ReactiveCocoa/ReactiveCocoa#3000](https://github.com/ReactiveCocoa/ReactiveCocoa/issues/3000), but how can i use it

**Comment by mhuusko5** [comment]
You'd have to put them in a private specs repo (I have them working that way).

Hopefully soon, they could be pushed to the respective Reactive repos, and then pushed to CP trunk. But I'm guessing it would be best to wait until the repos do their first/next GH release in their new organisation, so that we can be sure about the versions/point to a tag instead of a commit.

@ashfurrow thoughts?

**Comment by loveforgeter** [comment]
@mhuusko5  Thanks,  I made it working.
