### ISSUE TITLE
[Request] ReactiveCocoa Podspec update for 4.2 version

### ISSUE THREAD

**Issue by minuscorp** [mhuusko5/Podspecs#9]
The title says it all! Thank you very much!

**Comment by orta** [comment]
You're welcome to send a pull request adding it.

**Comment by minuscorp** [comment]
I'll try to figure out how could I do it, but I requested it because I have no idea how should I do it.

Jorge Revuelta Herrero
Software Engineer
BISITE Research Group

**Comment by minuscorp** [comment]
I've opened a PR with this

**Comment by christian-public** [comment]
I have been in contact with @ashfurrow regarding this issue and he told me that the Podspec does not lint correctly (the linting errors are shown at the bottom). I have tried to investigate the issues and have figured out the following:

I think there are two main issues:
1. [ReactiveCocoa/UI] `'UIBarButtonItem+RACCommandSupport.h' file not found` is reported because the file is missing from the tvOS target. This one can easily be fixed by adding the `UIBarButtonItem` to the ss.tvos.source_files property.
2. [ReactiveCocoa/Core] `'ReactiveCocoa/ReactiveCocoa.h' file not found` is reported because the generated ReactiveCocoa.framework/Headers/ReactiveCocoa-Swift.h tries to `#import <ReactiveCocoa/ReactiveCocoa.h>` but the header file (ReactiveCocoa/ReactiveCocoa.h) is excluded from the ReactiveCocoa/Core-subspec.

If I include ReactiveCocoa/ReactiveCocoa.h file for the ReactiveCocoa/Core-subspec I meet another problem: The header file contains references to all the UI headers, which will fail with errors similar to `'UIBarButtonItem+RACCommandSupport.h' file not found`. This is only a problem when building the ReactiveCocoa/Core-subspec as a standalone module (without the UI).

To summarize:
- When building the ReactiveCocoa/Core-subspec the header file (ReactiveCocoa/ReactiveCocoa.h) **should not** include the UI headers.
- When building the ReactiveCocoa/UI-subspec the header file (ReactiveCocoa/ReactiveCocoa.h) **should** include the UI headers.

I am not sure how to differentiate between these two cases.

```
 -> ReactiveCocoa (4.2.0)
    - WARN  | [ReactiveCocoa/Core,ReactiveCocoa/UI] xcodebuild:  ReactiveCocoa/ReactiveCocoa/Objective-C/RACCompoundDisposable.m:85:12: warning: unused variable 'result' [-Wunused-variable]
    - WARN  | [ReactiveCocoa/Core,ReactiveCocoa/UI] xcodebuild:  ReactiveCocoa/ReactiveCocoa/Objective-C/RACCompoundDisposable.m:132:12: warning: unused variable 'result' [-Wunused-variable]
    - WARN  | [ReactiveCocoa/Core,ReactiveCocoa/UI] xcodebuild:  ReactiveCocoa/ReactiveCocoa/Objective-C/RACSerialDisposable.m:63:12: warning: unused variable 'result' [-Wunused-variable]
    - WARN  | [ReactiveCocoa/Core,ReactiveCocoa/UI] xcodebuild:  ReactiveCocoa/ReactiveCocoa/Objective-C/RACSerialDisposable.m:79:12: warning: unused variable 'result' [-Wunused-variable]
    - ERROR | [ReactiveCocoa/Core,ReactiveCocoa/UI] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - NOTE  | [ReactiveCocoa/UI] xcodebuild:  <module-includes>:1:9: note: in file included from <module-includes>:1:
    - NOTE  | [ReactiveCocoa/UI] xcodebuild:  Target Support Files/ReactiveCocoa/ReactiveCocoa-umbrella.h:75:9: note: in file included from Target Support Files/ReactiveCocoa/ReactiveCocoa-umbrella.h:75:
    - ERROR | [ReactiveCocoa/UI] xcodebuild:  ReactiveCocoa/ReactiveCocoa/ReactiveCocoa.h:67:10: error: 'UIBarButtonItem+RACCommandSupport.h' file not found
    - NOTE  | [ReactiveCocoa/Core,ReactiveCocoa/UI] xcodebuild:  <unknown>:0: error: could not build Objective-C module 'ReactiveCocoa'
    - NOTE  | [ReactiveCocoa/Core] xcodebuild:  <module-includes>:2:9: note: in file included from <module-includes>:2:
    - ERROR | [iOS] [ReactiveCocoa/Core] xcodebuild:  /Users/skohorn/Library/Developer/Xcode/DerivedData/App-gnksmemzphtghfdqgqlqkwopizxy/Build/Products/Release-iphonesimulator/ReactiveCocoa/ReactiveCocoa.framework/Headers/ReactiveCocoa-Swift.h:100:9: error: 'ReactiveCocoa/ReactiveCocoa.h' file not found
    - ERROR | [OSX] [ReactiveCocoa/Core] xcodebuild:  /Users/skohorn/Library/Developer/Xcode/DerivedData/App-gnksmemzphtghfdqgqlqkwopizxy/Build/Products/Release/ReactiveCocoa/ReactiveCocoa.framework/Headers/ReactiveCocoa-Swift.h:100:9: error: 'ReactiveCocoa/ReactiveCocoa.h' file not found
    - ERROR | [tvOS] [ReactiveCocoa/Core] xcodebuild:  /Users/skohorn/Library/Developer/Xcode/DerivedData/App-gnksmemzphtghfdqgqlqkwopizxy/Build/Products/Release-appletvsimulator/ReactiveCocoa/ReactiveCocoa.framework/Headers/ReactiveCocoa-Swift.h:100:9: error: 'ReactiveCocoa/ReactiveCocoa.h' file not found
    - ERROR | [watchOS] [ReactiveCocoa/Core] xcodebuild:  /Users/skohorn/Library/Developer/Xcode/DerivedData/App-gnksmemzphtghfdqgqlqkwopizxy/Build/Products/Release-watchsimulator/ReactiveCocoa/ReactiveCocoa.framework/Headers/ReactiveCocoa-Swift.h:100:9: error: 'ReactiveCocoa/ReactiveCocoa.h' file not found

Analyzed 1 podspec.

[!] The spec did not pass validation, due to 6 errors and 4 warnings.
```

**Comment by dmcrodrigues** [comment]
@chrrasmussen I've changed the podspec to include `UIBarButtonItem` on `ss.tvos.source_files` property and the podspec passed validation. I allowed warnings during the lint to ignore those unused variable warnings. I have not seen the error of `ReactiveCocoa/ReactiveCocoa.h`. Can you validate on your side if that fixes the issues?

I tested with both 4.2.0 and master.

**Comment by ashfurrow** [comment]
@dmcrodrigues can you open an PR with those changes? If they work locally, we can merge into `master` and deploy to CocoaPods trunk, which would be 💯 Thanks for your work everyone!

**Comment by dmcrodrigues** [comment]
Sure ✨ 👍

**Comment by christian-public** [comment]
@dmcrodrigues Thanks for testing! Unfortunately I still get the `'ReactiveCocoa/ReactiveCocoa.h' file not found` errors after including `UIBarButtonItem`. At least it removes `'UIBarButtonItem+RACCommandSupport.h' file not found` error.

I tested again by running `pod spec lint --allow-warnings` (using Xcode v7.3.1 and CocoaPods v1.0.1).

Maybe someone else could try as well.

**Comment by dmcrodrigues** [comment]
Oh I'm still using CocoaPods v0.39.0 😞

**Comment by ashfurrow** [comment]
I've got some free time now, I'll take a look and let everyone know.

**Comment by ashfurrow** [comment]
Just an update on this: looks like some recent restructuring has led to the removal of the `no-arc` subspec, so we can get rid of that. The problem appears to be with the Core subspec: it can't access the included [ReactiveCocoa.h](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/6f52f8bbdf1118431b3984a1e2858e6eecf444e6/ReactiveCocoa/ReactiveCocoa.h) file because of the `#if TARGET`. 

A fix might be to stop relying on ReactiveCocoa's header and just use one generated by CocoaPods, not sure. It's been a while since I've worked on this. I'm also wondering if it's worth keeping the Core subspec around.

**Comment by ashfurrow** [comment]
@orta do you remember which pod we were working with that had its own header that caused issues? I can't remember how we fixed that.

**Comment by orta** [comment]
I think it was RAC - though I think we did that before this repo

**Comment by ashfurrow** [comment]
Ha, maybe! Seems like the generated ReactiveCocoa-Swift.h file is trying to `#import <ReactiveCocoa/ReactiveCocoa.h>` but if I do a `--no-clean` and comment that line out, it builds.

**Comment by ashfurrow** [comment]
Okay, I've hit a wall. I've trimmed down the podspec to basically nothing (just an iOS target) and when I lint I'm still getting the same error. Using CocoaPods 1.0.1, here's the output:

(Edit: I'm running this command in a directory where I've cloned the ReactiveCocoa repo, so using `pod lib lint` instead of `pod spec lint`.)

``` sh
> pod lib lint ReactiveCocoa.podspec --verbose --no-clean --allow-warnings

...

 -> ReactiveCocoa (4.2.1)
    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code.
    - NOTE  | [iOS] xcodebuild:  <module-includes>:2:9: note: in file included from <module-includes>:2:
    - ERROR | [iOS] xcodebuild:  /Users/ash/Library/Developer/Xcode/DerivedData/App-fctegugttlqsjjegqurjwjwshruv/Build/Products/Release-iphonesimulator/ReactiveCocoa/ReactiveCocoa.framework/Headers/ReactiveCocoa-Swift.h:100:9: error: 'ReactiveCocoa/ReactiveCocoa.h' file not found
    - NOTE  | [iOS] xcodebuild:  <unknown>:0: error: could not build Objective-C module 'ReactiveCocoa'
```

(That output is trimmed.)

I feel like there's something easy here that I'm not getting. If I remember right, CocoaPods creates a MODULENAME/MODULENAME.h header file for Objective-C code, right? But when it's trying to reference that file in the Swift generated header, it breaks.

**Comment by orta** [comment]
RAC isn't the only big ObjC + Swift lib, try compare how things are in comparison to [Quick](https://github.com/Quick/Quick/blob/master/Quick.podspec) - it's Podspec is very simple, RAC is probably doing something weird somewhere.

**Comment by orta** [comment]
For example, here's it's `Quick.h` - https://github.com/Quick/Quick/blob/master/Sources/Quick/Quick.h

**Comment by ashfurrow** [comment]
Yeah, it's all these device-specific imports. I'm just deleting ReactiveCocoa.h in the `prepare_command` so we use the CocoaPods-generated one instead. Thought using theirs might work without a Core subspec.

**Comment by orta** [comment]
👍

**Comment by ashfurrow** [comment]
Hmm, yeah. I think that's the way to go: rely on theirs and get rid of Core. Just got it to lint locally.

**Comment by ashfurrow** [comment]
I've opened #12 to fix this, if anyone is able to take a look, I'd appreciate it.

**Comment by ashfurrow** [comment]
@minuscorp this has been pushed to CocoaPods trunk: https://raw.githubusercontent.com/CocoaPods/Specs/56eed52fc375a62fefb518a0547e904fa76efd45/Specs/ReactiveCocoa/4.2.1/ReactiveCocoa.podspec.json
